<!DOCTYPE html>
<html lang="ru">
<head>
    <title>
        11.5 | Задача 1
    </title>
</head>
<body>

    <script>

        let names = ['iliakan', 'remy', 'jeresig'];

        let requests = names.map(name => fetch(`https://api.github.com/users/${name}`));

        Promise.all(requests)
            .then(responses => {
                // все промисы успешно завершены
                for(let response of responses) {
                    alert(`${response.url}: ${response.status}`); // покажет 200 для каждой ссылки
                }

                return responses;
            })
            // преобразовать массив ответов response в response.json(),
            // чтобы прочитать содержимое каждого
            .then(responses => Promise.all(responses.map(r => r.json())))
            // все JSON-ответы обработаны, users - массив с результатами
            .then(users => users.forEach(user => alert(user.name)));

        // Если любой из промисов завершится с ошибкой, то промис, возвращённый Promise.all, немедленно завершается с этой ошибкой.
        // Например:

        Promise.all([
            new Promise((resolve, reject) => setTimeout(() => resolve(1), 1000)),
            new Promise((resolve, reject) => setTimeout(() => reject(new Error("Ошибка!")), 2000)),
            new Promise((resolve, reject) => setTimeout(() => resolve(3), 3000))
        ]).catch(alert); // Error: Ошибка!

        // Здесь второй промис завершится с ошибкой через 2 секунды.
        // Это приведёт к немедленной ошибке в Promise.all,
        // так что выполнится .catch: ошибка этого промиса становится ошибкой всего Promise.all.

        // В случае ошибки, остальные результаты игнорируются

        //=======================

        // Например, мы хотели бы загрузить информацию о множестве пользователей. Даже если в каком-то запросе ошибка, нас всё равно интересуют остальные.
        // Используем для этого Promise.allSettled:

        let urls = [
            'https://api.github.com/users/iliakan',
            'https://api.github.com/users/remy',
            'https://no-such-url'
        ];

        Promise.allSettled(urls.map(url => fetch(url)))
            .then(results => { // (*)
                results.forEach((result, num) => {
                    if (result.status == "fulfilled") {
                        alert(`${urls[num]}: ${result.value.status}`);
                    }
                    if (result.status == "rejected") {
                        alert(`${urls[num]}: ${result.reason}`);
                    }
                });
            });

        // Массив results в строке (*) будет таким:
        [
            {status: 'fulfilled', value: ...объект ответа...},
            {status: 'fulfilled', value: ...объект ответа...},
            {status: 'rejected', reason: ...объект ошибки...}
        ]
        //То есть, для каждого промиса у нас есть его статус и значение/ошибка.

        //====================================

        // Promise.race
        // Метод очень похож на Promise.all, но ждёт только первый выполненный промис, из которого берёт результат (или ошибку).

        // Например, тут результат будет 1:

        Promise.race([
            new Promise((resolve, reject) => setTimeout(() => resolve(1), 1000)),
            new Promise((resolve, reject) => setTimeout(() => reject(new Error("Ошибка!")), 2000)),
            new Promise((resolve, reject) => setTimeout(() => resolve(3), 3000))
        ]).then(alert); // 1
        // Быстрее всех выполнился первый промис, он и дал результат. После этого остальные промисы игнорируются.

        //===================================

        // Promise.any
        // Метод очень похож на Promise.race, но ждёт только первый успешно выполненный промис, из которого берёт результат.

        // Если ни один из переданных промисов не завершится успешно, тогда возвращённый объект Promise будет отклонён
        // с помощью AggregateError – специального объекта ошибок, который хранит все ошибки промисов в своём свойстве errors.

        // Например, здесь, результатом будет 1:

        Promise.any([
            new Promise((resolve, reject) => setTimeout(() => reject(new Error("Ошибка!")), 1000)),
            new Promise((resolve, reject) => setTimeout(() => resolve(1), 2000)),
            new Promise((resolve, reject) => setTimeout(() => resolve(3), 3000))
        ]).then(alert); // 1

        // Вот пример, в котором все промисы отклоняются:

        Promise.any([
            new Promise((resolve, reject) => setTimeout(() => reject(new Error("Ошибка!")), 1000)),
            new Promise((resolve, reject) => setTimeout(() => reject(new Error("Ещё одна ошибка!")), 2000))
        ]).catch(error => {
            console.log(error.constructor.name); // AggregateError
            console.log(error.errors[0]); // Error: Ошибка!
            console.log(error.errors[1]); // Error: Ещё одна ошибка!
        });

    </script>

</body>
</html>